---
AWSTemplateFormatVersion: '2010-09-09'
Description: AWS EventBridge

Parameters:
  BusName:
    Type: String
    Description: Name of the event bus

Resources:
  EventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: rea.blue
      Tags:
        - Key: Team
          Value: Blue

  SchemaRegistry:
    Type: AWS::EventSchemas::Registry
    Properties:
      Description: Event schema registry for BlueTeam
      RegistryName: rea.blue
      Tags:
        - Key: Team
          Value: Blue

  SchemaRegistryPolicy:
    Type: AWS::EventSchemas::RegistryPolicy
    Properties:
      Policy:
        # https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-resource-based-schemas.html#eb-resource-policy-account-read
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Principal:
            AWS:
              - '881463952688'
              - '730845873532'
          Action:
            - schemas:DescribeRegistry
            - schemas:ListSchemas
            - schemas:SearchSchemas
            - schemas:DescribeSchema
            - schemas:ListSchemaVersions
            - schemas:DescribeCodeBinding
            - schemas:GetCodeBindingSource
          Resource:
            - Ref: SchemaRegistry
            - Fn::Join:
              - ''
              - - !Sub arn:aws:schemas:${AWS::Region}:${AWS::AccountId}:schema/
                - !GetAtt SchemaRegistry.RegistryName
                - '*'
      RegistryName: !GetAtt SchemaRegistry.RegistryName

  ServiceAJobStateChangeSchema:
    Type: AWS::EventSchemas::Schema
    Properties:
      Content: >
        {
          "openapi": "3.0.0",
          "info": {
            "version": "1.0.0",
            "title": "JobStateChange"
          },
          "paths": {},
          "components": {
            "schemas": {
              "REAEvent": {
                "type": "object",
                "required": ["detail-type", "resources", "id", "source", "time", "detail", "region", "version", "account"],
                "x-rea-events-detail-type": "Job State Change",
                "x-rea-events-source": "rea.blue.service-a",
                "properties": {
                  "detail": {
                    "$ref": "#/components/schemas/JobStateChange"
                  },
                  "detail-type": {
                    "type": "string"
                  },
                  "resources": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "id": {
                    "type": "string"
                  },
                  "source": {
                    "type": "string"
                  },
                  "time": {
                    "type": "string",
                    "format": "date-time"
                  },
                  "region": {
                    "type": "string"
                  },
                  "version": {
                    "type": "string"
                  },
                  "account": {
                    "type": "string"
                  }
                }
              },
              "JobStateChange": {
                "type": "object",
                "required": ["entityId", "userId", "status"],
                "properties": {
                  "entityId": {
                    "type": "string"
                  },
                  "userId": {
                    "type": "string"
                  },
                  "status": {
                    "type": "string",
                    "enum": ["SUBMITTED", "STARTED", "COMPLETED", "FAILED"]
                  }
                }
              }
            }
          }
        }
      Description: Job state change for service A
      RegistryName: !GetAtt SchemaRegistry.RegistryName
      SchemaName: rea.blue.service-a@JobStateChange
      Tags:
        - Key: Team
          Value: Blue
      Type: OpenApi3
