version: '3.9'
services:
  base: &base
    image: amazon/aws-cli:latest
    working_dir: /opt/code
    volumes:
      - ./:/opt/code
      - $HOME/.aws:/root/.aws
    environment:
      - AWS_DEFAULT_REGION=ap-southeast-2
      - AWS_PROFILE=sandbox01

  deploy:
    <<: *base
    command: cloudformation deploy
      --stack-name $StackName
      --template-file cloudformation.yml
      --capabilities CAPABILITY_NAMED_IAM
      --no-fail-on-empty-changeset
      --parameter-overrides
      BusName=$BusName
